# Generated by Django 3.1.1 on 2020-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201104_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
