# Generated by Django 3.1.1 on 2020-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/media/user_avatars/default.jpg', upload_to='user_avatars'),
        ),
    ]
