# Generated by Django 3.1.1 on 2020-11-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20201117_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(default='/user_avatars/default.jpg'),
        ),
    ]
