# Generated by Django 3.1.1 on 2020-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20201124_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(default='https://alphasquad.herokuapp.com/user_avatars/default.jpg'),
        ),
    ]
