# Generated by Django 3.1.1 on 2020-10-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinder', '0002_event_author'),
        ('eventFinder', '0004_auto_20201020_2141'),
    ]

    operations = [
    ]
