# Generated by Django 3.1.1 on 2020-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinder', '0006_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='Generic Event Description', max_length=1000),
        ),
    ]
