# Generated by Django 3.1.1 on 2020-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinder', '0007_auto_20201105_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
