# Generated by Django 3.1.1 on 2020-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinder', '0008_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=38.0336, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=-78.50798, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='No Description Provided', max_length=1000),
        ),
    ]
